# Site settings
title: Emily Jane McTavish
email: ejmctavish@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Assistant Professor, UC Merced 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://McTavishlab.github.io" # the base hostname & protocol for your site
twitter_username: snacktavish
github_username:  snacktavish
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
